// <auto-generated />
using System;
using MasterStack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterStack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208034304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("MasterStack.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("MasterStack.Models.BlogPostTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogPostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Culture");

                    b.HasIndex("BlogPostId", "Culture")
                        .IsUnique();

                    b.ToTable("BlogPostTranslations");
                });

            modelBuilder.Entity("MasterStack.Models.Language", b =>
                {
                    b.Property<string>("Culture")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasMaxLength(15)
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Culture");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Culture = "pt-BR",
                            FlagClass = "fi-br",
                            Id = 0,
                            IsActive = false,
                            Name = "Português"
                        },
                        new
                        {
                            Culture = "en-US",
                            FlagClass = "fi-us",
                            Id = 0,
                            IsActive = false,
                            Name = "English"
                        },
                        new
                        {
                            Culture = "fr-FR",
                            FlagClass = "fi-ca",
                            Id = 0,
                            IsActive = false,
                            Name = "Français"
                        });
                });

            modelBuilder.Entity("MasterStack.Models.BlogPostTranslation", b =>
                {
                    b.HasOne("MasterStack.Models.BlogPost", "BlogPost")
                        .WithMany("Translations")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterStack.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("MasterStack.Models.BlogPost", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
