//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterStack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterStack.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Project.
        /// </summary>
        public static string AboutSection {
            get {
                return ResourceManager.GetString("AboutSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built with best practices.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Blog.
        /// </summary>
        public static string AdminBlog {
            get {
                return ResourceManager.GetString("AdminBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search.
        /// </summary>
        public static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Performance.
        /// </summary>
        public static string Feature1Title {
            get {
                return ResourceManager.GetString("Feature1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string FooterContact {
            get {
                return ResourceManager.GetString("FooterContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string FooterPrivacy {
            get {
                return ResourceManager.GetString("FooterPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate C# with microcontrollers and electronics for a connected world..
        /// </summary>
        public static string HardwareDesc {
            get {
                return ResourceManager.GetString("HardwareDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware &amp; IoT.
        /// </summary>
        public static string HardwareTitle {
            get {
                return ResourceManager.GetString("HardwareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ultimate tech stack.
        /// </summary>
        public static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost your Development.
        /// </summary>
        public static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string MenuBlog {
            get {
                return ResourceManager.GetString("MenuBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string MenuFeatures {
            get {
                return ResourceManager.GetString("MenuFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string MenuTutorials {
            get {
                return ResourceManager.GetString("MenuTutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-performance apps with .NET MAUI and native iOS/Android integration.
        /// </summary>
        public static string MobileDesc {
            get {
                return ResourceManager.GetString("MobileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Edge.
        /// </summary>
        public static string MobileTitle {
            get {
                return ResourceManager.GetString("MobileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for.
        /// </summary>
        public static string SearchResultsFor {
            get {
                return ResourceManager.GetString("SearchResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalable architectures using .NET 9, Clean Architecture, and Cloud Computing..
        /// </summary>
        public static string WebDesc {
            get {
                return ResourceManager.GetString("WebDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Development.
        /// </summary>
        public static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer working on integrated technology projects..
        /// </summary>
        public static string WhyMasterstackAlt {
            get {
                return ResourceManager.GetString("WhyMasterstackAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We combine the power of modern web development with mobile agility and hardware precision. Our mission is to provide high-quality tutorials for those looking to build complete, scalable real-world solutions..
        /// </summary>
        public static string WhyText {
            get {
                return ResourceManager.GetString("WhyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why choose MasterStack?.
        /// </summary>
        public static string WhyTitle {
            get {
                return ResourceManager.GetString("WhyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca uma string localizada semelhante a Nome de Exibição.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca uma string localizada semelhante a Biografia.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }

         public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }

        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        public static string MaxLengthError {
            get {
                return ResourceManager.GetString("MaxLengthError", resourceCulture);
            }
        }

        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }

        

        public static string EmailChangeDisabled {
            get {
                return ResourceManager.GetString("EmailChangeDisabled", resourceCulture);
            }
        }

        public static string Blog_PostNotAvailableTitle {
            get {
                return ResourceManager.GetString("Blog_PostNotAvailableTitle", resourceCulture);
            }
        }

        public static string Blog_PostNotAvailableMessage {
            get {
                return ResourceManager.GetString("Blog_PostNotAvailableMessage", resourceCulture);
            }
        }

       public static string Profile_Bio { get { return ResourceManager.GetString("Profile_Bio", resourceCulture); } }
public static string Profile_Bio_PT { get { return ResourceManager.GetString("Profile_Bio_PT", resourceCulture); } }
public static string Profile_Bio_EN { get { return ResourceManager.GetString("Profile_Bio_EN", resourceCulture); } }
public static string Profile_Bio_FR { get { return ResourceManager.GetString("Profile_Bio_FR", resourceCulture); } }
public static string Profile_Author_Translations { get { return ResourceManager.GetString("Profile_Author_Translations", resourceCulture); } }
public static string ChangePhoto { get { return ResourceManager.GetString("ChangePhoto", resourceCulture); } }
public static string PublicInformation { get { return ResourceManager.GetString("PublicInformation", resourceCulture); } }

public static string SaveProfile { get { return ResourceManager.GetString("SaveProfile", resourceCulture); } }
public static string SuccessTitle { get { return ResourceManager.GetString("SuccessTitle", resourceCulture); } }
public static string ErrorFormMessage { get { return ResourceManager.GetString("ErrorFormMessage", resourceCulture); } }
    }
}
