//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterStack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterStack.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Project.
        /// </summary>
        public static string AboutSection {
            get {
                return ResourceManager.GetString("AboutSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built with best practices.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Performance.
        /// </summary>
        public static string Feature1Title {
            get {
                return ResourceManager.GetString("Feature1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate C# with microcontrollers and electronics for a connected world..
        /// </summary>
        public static string HardwareDesc {
            get {
                return ResourceManager.GetString("HardwareDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware &amp; IoT.
        /// </summary>
        public static string HardwareTitle {
            get {
                return ResourceManager.GetString("HardwareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ultimate tech stack.
        /// </summary>
        public static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost your Development.
        /// </summary>
        public static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string MenuFeatures {
            get {
                return ResourceManager.GetString("MenuFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string MenuTutorials {
            get {
                return ResourceManager.GetString("MenuTutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-performance apps with .NET MAUI and native iOS/Android integration.
        /// </summary>
        public static string MobileDesc {
            get {
                return ResourceManager.GetString("MobileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Edge.
        /// </summary>
        public static string MobileTitle {
            get {
                return ResourceManager.GetString("MobileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalable architectures using .NET 9, Clean Architecture, and Cloud Computing..
        /// </summary>
        public static string WebDesc {
            get {
                return ResourceManager.GetString("WebDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Development.
        /// </summary>
        public static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer working on integrated technology projects..
        /// </summary>
        public static string WhyMasterstackAlt {
            get {
                return ResourceManager.GetString("WhyMasterstackAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We combine the power of modern web development with mobile agility and hardware precision. Our mission is to provide high-quality tutorials for those looking to build complete, scalable real-world solutions..
        /// </summary>
        public static string WhyText {
            get {
                return ResourceManager.GetString("WhyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why choose MasterStack?.
        /// </summary>
        public static string WhyTitle {
            get {
                return ResourceManager.GetString("WhyTitle", resourceCulture);
            }
        }
    }
}
